src/JustBlog/JustBlog/Controllers/BlogController.cs
#region Usings
using System;
using System.Configuration;
using System.Linq;
using System.Net.Mail;
using System.ServiceModel.Syndication;
using System.Text;
using System.Web;
using System.Web.Mvc;
using JustBlog.Core;
using JustBlog.Core.Objects;
using JustBlog.Models;
#endregion

namespace JustBlog.Controllers
{
  /// <summary>
  /// Home controller that contain actions to return list/view pages and others.
  /// </summary>
  public class BlogController: Controller
  {
    private readonly IBlogRepository _blogRepository;

    public BlogController(IBlogRepository blogRepository)
    {
      _blogRepository = blogRepository;
    }

    /// <summary>
    /// Return the list page with latest posts.
    /// </summary>
    /// <param name="p">pagination number</param>
    /// <returns></returns>
    public ViewResult Posts(int p = 1)
    {
      var viewModel = new ListViewModel(_blogRepository, p);
      ViewBag.Title = "Latest Posts";
      return View("List", viewModel);
    }

    /// <summary>
    /// Return a particular post based on the puslished year, month and url slug.
    /// </summary>
    /// <param name="year">Published year</param>
    /// <param name="month">Published month</param>
    /// <param name="title">Url slug</param>
    /// <returns></returns>
    public ViewResult Post(int year, int month, string title)
    {
      var post = _blogRepository.Post(year, month, title);

      if (post == null)
        throw new HttpException(404, "Post not found");

      if (post.Published == false && User.Identity.IsAuthenticated == false)
        throw new HttpException(401, "The post is not published");

      return View(post);
    }

    /// <summary>
    /// Return the posts belongs to a category.
    /// </summary>
    /// <param name="category">Url slug</param>
    /// <param name="p">Pagination number</param>
    /// <returns></returns>
    public ViewResult Category(string category, int p = 1)
    {
      var viewModel = new ListViewModel(_blogRepository, category, "Category", p);

      if (viewModel.Category == null)
        throw new HttpException(404, "Category not found");

      ViewBag.Title = String.Format(@"Latest posts on category ""{0}""", viewModel.Category.Name);
      return View("List", viewModel);
    }

    /// <summary>
    /// Return the posts belongs to a tag.
    /// </summary>
    /// <param name="tag">Url slug</param>
    /// <param name="p">Pagination number</param>
    /// <returns></returns>
    public ViewResult Tag(string tag, int p = 1)
    {
      var viewModel = new ListViewModel(_blogRepository, tag, "Tag", p);

      if (viewModel.Tag == null)
        throw new HttpException(404, "Tag not found");

      ViewBag.Title = String.Format(@"Latest posts tagged on ""{0}""", viewModel.Tag.Name);
      return View("List", viewModel);
    }

    /// <summary>
    /// Return the posts that matches the search text.
    /// </summary>
    /// <param name="s">search text</param>
    /// <param name="p">Pagination number</param>
    /// <returns></returns>
    public ViewResult Search(string s, int p = 1)
    {
      ViewBag.Title = String.Format(@"Lists of posts found for search text ""{0}""", s);

      var viewModel = new ListViewModel(_blogRepository, s, "Search", p);
      return View("List", viewModel);
    }

    /// <summary>
    /// Child action that returns the sidebar partial view.
    /// </summary>
    /// <returns></returns>
    [ChildActionOnly]
    public PartialViewResult Sidebars()
    {
      var widgetViewModel = new WidgetViewModel(_blogRepository);
      return PartialView("_Sidebars", widgetViewModel);
    }

    /// <summary>
    /// Return the contact form.
    /// </summary>
    /// <returns></returns>
    public ViewResult Contact()
    {
      return View();
    }

    /// <summary>
    /// Send an email to the blog admin from the POSTed contact form.
    /// </summary>
    /// <param name="contact"></param>
    /// <returns></returns>
    [HttpPost]
    public ViewResult Contact(Contact contact)
    {
      if (ModelState.IsValid)
      {
        using (var client = new SmtpClient())
        {
          var adminEmail = ConfigurationManager.AppSettings["AdminEmail"];
          var from = new MailAddress(adminEmail, "JustBlog Messenger");
          var to = new MailAddress(adminEmail, "JustBlog Admin");

          using (var message = new MailMessage(from, to))
          {
            message.Body = contact.Body;
            message.IsBodyHtml = true;
            message.BodyEncoding = Encoding.UTF8;

            message.Subject = contact.Subject;
            message.SubjectEncoding = Encoding.UTF8;

            message.ReplyTo = new MailAddress(contact.Email);

            client.Send(message);
          }
        }

        return View("Thanks");
      }

      return View();
    }

    /// <summary>
    /// Return the About me page.
    /// </summary>
    /// <returns></returns>
    public ViewResult Aboutme()
    {
      return View();
    }

    /// <summary>
    /// Generate and return RSS feed.
    /// </summary>
    /// <returns></returns>
    public ActionResult Feed()
    {
      var blogTitle = ConfigurationManager.AppSettings["BlogTitle"];
      var blogDescription = ConfigurationManager.AppSettings["BlogDescription"];
      var blogUrl = ConfigurationManager.AppSettings["BlogUrl"];

      var posts = _blogRepository.Posts(0, 25).Select
      (
          p => new SyndicationItem
              (
                  p.Title,
                  p.Description,
                  new Uri(string.Concat(blogUrl, p.Href(Url)))
              )
      );

      var feed = new SyndicationFeed(blogTitle, blogDescription, new Uri(blogUrl), posts)
      {
        Copyright = new TextSyndicationContent(String.Format("Copyright © {0}", blogTitle)),
        Language = "en-US"
      };

      return new FeedResult(new Rss20FeedFormatter(feed));
    }
  }
}

src/JustBlog/JustBlog/Views/Shared/_AddThis.cshtml
<!-- AddThis Widget -->

@model JustBlog.Core.Objects.Post

@{
  var addThisUrl = System.Configuration.ConfigurationManager.AppSettings["AddThisUrl"];
}

<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
  <a class="addthis_button_preferred_1" addthis:url="@(string.Format("http://www.prideparrot.com{0}", Model.Href(Url)))" addthis:title="@Model.Title" addthis:description="@Model.Meta"></a>
  <a class="addthis_button_preferred_2" addthis:url="@(string.Format("http://www.prideparrot.com{0}", Model.Href(Url)))" addthis:title="@Model.Title" addthis:description="@Model.Meta"></a>
  <a class="addthis_button_preferred_3" addthis:url="@(string.Format("http://www.prideparrot.com{0}", Model.Href(Url)))" addthis:title="@Model.Title" addthis:description="@Model.Meta"></a>
  <a class="addthis_button_preferred_4" addthis:url="@(string.Format("http://www.prideparrot.com{0}", Model.Href(Url)))" addthis:title="@Model.Title" addthis:description="@Model.Meta"></a>
  <a class="addthis_button_compact" addthis:url="@(string.Format("http://www.prideparrot.com{0}", Model.Href(Url)))" addthis:title="@Model.Title" addthis:description="@Model.Meta"></a>
  <a class="addthis_counter addthis_bubble_style" addthis:url="@(string.Format("http://www.prideparrot.com{0}", Model.Href(Url)))" addthis:title="@Model.Title" addthis:description="@Model.Meta"></a>
</div>

<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>

<script type="text/javascript" src="@addThisUrl"></script>
<!-- AddThis Button END -->

src/JustBlog/JustBlog/Views/Shared/_Categories.cshtml
@model IList<JustBlog.Core.Objects.Category>

<!-- Widget to display categories in sidebar -->
<div class="sidebar">
  <h3>Categories</h3>

  @if (Model.Count > 0)
  {
    <ul>
      @foreach (var category in Model)
      {
        <li>@Html.CategoryLink(category)</li>
      }
    </ul>
  }
  else
  {
    <p>No categories found!</p>
  }
</div>

src/JustBlog/JustBlog/Views/Shared/_Disqus.cshtml
@model JustBlog.Core.Objects.Post

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = '@System.Configuration.ConfigurationManager.AppSettings["Domain"]'; // required: replace example with your forum shortname
    var disqus_identifier =  '@Model.Href(Url)';
    var disqus_url = '@string.Format("http://{0}.com{1}", System.Configuration.ConfigurationManager.AppSettings["Domain"], Model.Href(Url))';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = false;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = '@System.Configuration.ConfigurationManager.AppSettings["Domain"]'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>

src/JustBlog/JustBlog/Views/Shared/_LatestPosts.cshtml
@model IList<JustBlog.Core.Objects.Post>

<!-- Widget to display latest posts in sidebar -->
<div class="sidebar">
  <h3>Latest Posts</h3>

  @if (Model.Count > 0)
  {
    <ul>
      @foreach (var post in Model)
      {
        <li>@Html.PostLink(post)</li>
      }
    </ul>
  }
  else
  {
    <p>No posts found!</p>
  }
</div>

src/JustBlog/JustBlog/Views/Shared/_Layout.cshtml
@using System.Configuration

@{
  Layout = null;
  var action = ((string)ViewContext.RouteData.Values["Action"]).ToLower();

  var blogTitle = ConfigurationManager.AppSettings["BlogTitle"];
  var feedBurnerUrl = ConfigurationManager.AppSettings["FeedBurnerUrl"];
}

<!DOCTYPE html>

<html>

<head>

  <meta name="viewport" content="width=device-width" />

  <title>@ViewBag.Title</title>

  <meta name="keywords" content="@(ViewBag.Keywords ?? ConfigurationManager.AppSettings["MetaKeywords"])" />
  <meta name="description" content="@(ViewBag.Description ?? ConfigurationManager.AppSettings["MetaDescription"])"/>
  <meta name="author" content="@ConfigurationManager.AppSettings["Author"]"/>

  @Styles.Render("~/Content/themes/simple/css")
  @Scripts.Render("~/jquery", "~/jqueryval", "~/jqueryunobtrusiveval", "~/js")
</head>
<body>

  <div id="main">

    <!-- Header & Navigation -->
    <div id="header">
      <div id="logo">
        <div id="logo_text">
          <h1><a href="/"><span class="logo_colour">@blogTitle</span></a></h1>
          <h2>Writings, Experiments and More...</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
          <li class="@(new[] { "posts", "post", "tag", "category", "search" }.Contains(action) ? "selected" : "")">@Html.ActionLink("Posts", "Posts")</li>
          <li class="@(action == "contact" ? "selected" : "")">@Html.ActionLink("Contact", "Contact")</li>
          <li class="@(action == "aboutme" ? "selected" : "")">@Html.ActionLink("About Me", "Aboutme")</li>
        </ul>
      </div>
    </div>

    <!-- Main Content -->
    <div id="site_content">

      <div class="feeddiv">
        <a href="@feedBurnerUrl" title="Subscribe to my blog">Subscribe to my blog</a>
      </div>

      @Html.Partial("_Search")
      @RenderBody()
      @Html.Action("Sidebars")
    </div>

    <!-- Footer -->
    <div id="footer">
      Copyright © @DateTime.Now.Year @blogTitle All Rights Reserved 
    </div>
  </div>
</body>
</html>

src/JustBlog/JustBlog/Views/Shared/_Pager.cshtml
@model JustBlog.Models.ListViewModel

@{
  var currentPage = ViewContext.RequestContext.HttpContext.Request["p"] != null ? int.Parse(ViewContext.RequestContext.HttpContext.Request["p"]) : 1;
  var totalPages = Math.Ceiling((double)Model.TotalPosts / 10);  
}

@if (currentPage > 1 || currentPage < totalPages)
{
  var p = string.Format("p={0}", currentPage - 1);
  var n = string.Format("p={0}", currentPage + 1);

  if (ViewContext.RouteData.Values["action"].ToString().Equals("search", StringComparison.OrdinalIgnoreCase))
  {
    var s = String.Format("?s={0}", ViewContext.RequestContext.HttpContext.Request.QueryString["s"]);
    p = String.Format("{0}&{1}", s, p);
    n = String.Format("{0}&{1}", s, n);
  }
  else
  {
    p = String.Concat("?", p);
    n = String.Concat("?", n);
  }
  
  <div class="pager">
    <a href="@p" title="Previous" class="previous" style="visibility:@(currentPage > 1 ? "visible" : "collapse")"><< previous</a>
    <a href="@n" title="Next" class="next" style="visibility:@(currentPage < totalPages ? "visible" : "collapse")">next >></a>
  </div>
}

src/JustBlog/JustBlog/Views/Shared/_PostTemplate.cshtml
@model JustBlog.Core.Objects.Post

<div class="post">
  <div class="post-meta">
    <div class="row">
      <div class="post-title">
        <h2>@Html.PostLink(Model)</h2>
      </div>
      <div class="share-links">
        @Html.Partial("_AddThis")
      </div>
    </div>
    <div class="row">
      <div class="post-category">
        <span>Category:&nbsp;</span>@Html.CategoryLink(Model.Category)
      </div>
      <div class="post-tags">
        <span>Tags:</span>@Helpers.Tags(Html, Model.Tags)
      </div>
      <div class="no-of-comments">
        <a href="@string.Format("{0}#disqus_thread", Model.Href(Url))"></a>
      </div>
      <div class="posted-date">
        @Model.PostedOn.ToConfigLocalTime()
      </div>
    </div>
  </div>
  <div class="post-body">
    @Html.Raw(Model.ShortDescription)
  </div>
  <div class="post-foot">
    @Html.ActionLink("continue...", "post", "blog", new { year = Model.PostedOn.Year, month = Model.PostedOn.Month, title = Model.UrlSlug }, new { title = "continue..." })
  </div>
</div>

src/JustBlog/JustBlog/Views/Shared/_Search.cshtml
@using (Html.BeginForm("Search", "Blog", FormMethod.Get, new { id = "search-form" }))
{
  <p>
    @Html.TextBox("s")
  </p>
  <p>
    <input type="submit" value="Search" />
  </p>
}
  

src/JustBlog/JustBlog/Views/Shared/_Sidebars.cshtml
@model JustBlog.Models.WidgetViewModel

<div id="sidebars">
  @Html.Partial("_Categories", Model.Categories)
  @Html.Partial("_Tags", Model.Tags)
  @Html.Partial("_LatestPosts", Model.LatestPosts)
</div>

src/JustBlog/JustBlog/Views/Shared/_Tags.cshtml
@model IList<JustBlog.Core.Objects.Tag>

<!-- Widget to display tags in sidebar -->
<div class="tags sidebar">
  <h3>Tags</h3>

  @if (Model.Count > 0)
  {
    foreach (var tag in Model)
    {
      @Html.TagLink(tag)
    }
  }
  else
  {
    <p>No tags found!</p>
  }
</div>